apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certsSecret }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ott_service_truststore.p12: {{ .Values.truststoreContent }}
  {{ .Values.moduleId }}.p12: {{ .Values.certstoreContent }}
type: Opaque
