apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.passwordsSecret }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  OTT_CERTSTORE_PRIVATE_KEY_PWD: {{ .Values.certstorePrivateKeyPwd }}
  OTT_CERTSTORE_PWD: {{ .Values.certstorePwd }}
  OTT_TRUST_STORE_PWD: {{ .Values.truststorePwd }}
type: Opaque
