apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.settingsConfigMap }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  OTT_MODULE_ID: {{ .Values.moduleId }}
  OTT_CLIENT_CERT_ALIAS: {{ .Values.moduleId | lower }}
  OTT_OPER_MODE: {{ .Values.operMode }}
  OTT_CERTSTORE_PATH: /mnt/secrets/{{ .Values.moduleId }}.p12
  OTT_SERVICE_HOSTS: {{ .Values.serviceHosts }}
  OTT_SERVICE_URL: {{ .Values.serviceUrl }}
  OTT_TRUST_STORE_PATH: /mnt/secrets/ott_service_truststore.p12
  # image defaults
  OTT_CLIENT_MMT-COMPATIBILITY-MODE: "false"
  OTT_GRPC_PORT: /mnt/ott-uds-socket/ott.socket
  OTT_CERTSTORE_TYPE: PKCS12
  OTT_SERVICE_CERT_ALIAS: ott-service
  OTT_AUTHZ_VERSION: "1.0"
  OTT_AUTHZ_REALM: ott
  OTT_HTTP_PORT: "8086"
  OTT_ANONYMOUS_REQUESTS_ENABLED: "false"
  OTT_CLIENT_DEFAULT_REALM: mmt
  OTT_CLIENT_MMT_RESOURCE_ATTRID: "urn:sbrf:names:pprb:1.0:api:interface:fullname"
  OTT_CLIENT_MMT_ACTION_ATTRID: "urn:sbrf:names:pprb:1.0:action:id"
  OTT_APPLICATION_ATTRIBUTE_ID: "urn:sbrf:names:pprb:1.0:module:id"
