---
# Source: synapse-backstage-ingress-service-egress/charts/subchart-egress/templates/egress.yaml
apiVersion: v1
kind: Service
metadata:
  name: egressgateway0-svc
  labels:
    app: egressgateway-demo-second
    istio: egressgateway-demo-second
    helm.sh/chart: subchart-egress-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ingress
spec:
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http-egr-8080
      port: 8080
      protocol: TCP
  selector:
    app: egressgateway-demo-second
    istio: egressgateway-demo-second
---
# Source: synapse-backstage-ingress-service-egress/charts/subchart-egress/templates/egress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egressgateway0-gw
  labels:
    helm.sh/chart: subchart-egress-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ingress
spec:
  selector:
    istio: egressgateway-demo-second
  servers:
    - hosts:
        - sytester-http-stub.default.svc.cluster.local
      port:
        name: http-8080
        number: 8080
        protocol: HTTP
---
# Source: synapse-backstage-ingress-service-egress/charts/subchart-egress/templates/egress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egressgateway0-se
  labels:
    helm.sh/chart: subchart-egress-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ingress
spec:
  exportTo:
    - .
  hosts:
    - sytester-http-stub.default.svc.cluster.local
  ports:
    - number: 80
      name: http-80
      protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
# Source: synapse-backstage-ingress-service-egress/charts/subchart-egress/templates/egress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egressgateway0-demo-second
  labels:
    helm.sh/chart: subchart-egress-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ingress
spec:
  exportTo:
    - .
  gateways:
    - egressgateway0-gw
    - mesh
  hosts:
    - sytester-http-stub.default.svc.cluster.local
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: egressgateway0-svc
            port:
              number: 8080
    - match:
        - gateways:
            - egressgateway0-gw
          port: 8080
      route:
        - destination:
            host: sytester-http-stub.default.svc.cluster.local
            port:
              number: 80
