apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8787
    protocol: TCP
  selector:
    app: test-app
  type: ClusterIP
