{{/* Input: .Release, .Chart, .context */}}
{{- define "ingress.gateway_certs" }}
apiVersion: v1
kind: Secret
metadata:
  name: ingressgateway{{ .context.hostNumber }}-ca-certs
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ca-chain.cert.pem: {{ .context.certs.caCert }}
type: opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ingressgateway{{ .context.hostNumber }}-certs
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  tls.crt: {{ .context.certs.certsCrt }}
  tls.key: {{ .context.certs.certsKey }}
type: opaque
{{- end }}{{/* define "ingress.gateway_certs" */}}
